tabWidth: 4
printWidth: 150
useTabs: false
overrides:
  - files: "*.component.html"
    options:
      parser: "angular"
  - files: "*.ts"
    options:
      singleQuote: true
      trailingComma: all
